### ISSUE TITLE
Top level inserter should only support sections

### ISSUE THREAD

**Issue by kjohnson** [impress-org/givewp-next-gen#22]
Related to #21, the top level block inserter should only support sections.

## Acceptance Criteria

- [x] Only unused section types are available in the inserter
- [ ] If all named sections are in use auto-insert a new custom section on click

**Comment by kjohnson** [comment]
Thinking through this again, this may be moot once parent/child block attributes are set as non-section blocks will always be child blocks and thus not available via the inserter at the top level.

**Comment by JasonTheAdams** [comment]
It may be worth reducing the section to a single click. If we know it's the only block, then we can just make it "Add Section", which adds a new section in a single click. Open to @jdghinson's thoughts on this as well.

**Comment by kjohnson** [comment]
Yeah, that makes sense. I'll update this issue to reflect that workflow.

**Comment by kjohnson** [comment]
> If all named sections are in use auto-insert a new custom section on click

I'm second guessing this - it sounds nice, but if all "named" sections are added by default then the user is never introduced to those "named" sections in the section inserter. So, if a section gets removed it would be unclear how to add it back, as the default behavior of the section inserter would effectively be to always insert a Custom Section.

/cc @jdghinson

**Comment by kjohnson** [comment]
Closing this for now - we can re-address this at a later time.
