### ISSUE TITLE
[Something] should...

### ISSUE THREAD

**Issue by Drbilal12** [impress-org/givewp-next-gen#253]
## Acceptance Criteria

-   [ ] Something happens when an action is taken.
-   [ ] Something does not happen when an action is taken.
-   [ ] Fixing behavior in Component A does not affect existing behavior in Component B.

**Comment by JoshuaHungDinh** [comment]
Hello @Drbilal12,

We wanted to inform you that we are currently in the process of archiving this repository and are in the midst of transitioning the codebase to a new location. Consequently, we won't be actively addressing any issues or pull requests here any longer.

It appears that no information has been posted in this particular issue. However, if you have come across any issues or if you'd like to provide us with feedback, we kindly ask that you create a new post on our feedback platform at: https://feedback.givewp.com/
