### ISSUE TITLE
Update default title, description in Payment Details section

### ISSUE THREAD

**Issue by kjohnson** [impress-org/givewp-next-gen#29]
(Converted from project board)

**Comment by kjohnson** [comment]
@JasonTheAdams this is already the default behavior.

By default, the sections are as follows, with the "Payment Details" section as the third section.

```
<!-- wp:custom-block-editor/donation-amount /-->
<!-- wp:custom-block-editor/donor-info /-->
<!-- wp:custom-block-editor/payment-details /-->
```

The "Payment Details" section consists of only the "Payment Gateways" block:

```
[ 'custom-block-editor/payment-gateways', { lock: { remove: true } }  ]
```

| Payment Details Section |
|---|
| ![Image](https://user-images.githubusercontent.com/10858303/177845479-a2b61df1-2b6a-4cf0-9787-9b00fcd3d9de.png) |

**Comment by JasonTheAdams** [comment]
@kjohnson Oh. Must be the local caching thing, again. Glad to hear it's already in there! Mind quickly replacing "payment details will go here :)" with "How would you like to pay for your donation?"

**Comment by kjohnson** [comment]
@JasonTheAdams can do - I'll update those default strings.
