### ISSUE TITLE
Question to help beta-testing

### ISSUE THREAD

**Issue by Rik44444** [impress-org/givewp-next-gen#38]
hi all,
great that the new visual form builder is coming. I wanted to help beta-test it, but i'm having some trouble trying to install it. Could someone help with this? I did not understand your instructions for Getting Set Up [here](https://github.com/impress-org/givewp-next-gen), so i just tried to download the zip, uploaded it to the plugins on a clone of our site, and then activated it. However, this crashed our site. I can share the error if that helps. 
Would love to be able to beta-test it, so if someone could help with this that would be great.
Rik

**Comment by kjohnson** [comment]
Hey @Rik44444, thanks for the interest in beta testing and poking around the repo 💪🏻 .

We have formal plans for a public Alpha and Beta phases coming soon, so I would suggest holding off for the time being with installing this plugin. These official testing phases will help us to field and respond to feedback properly.

In the meantime, I'll point you to the automated build hosted on GitHub pages for _sneak_ previewing the Form Builder: https://impress-org.github.io/givewp-next-gen/develop

**Comment by Rik44444** [comment]
ah excellent, OK i'll wait for the public Alpha/Beta then, thanks,
Rik
