### ISSUE TITLE
Form inputs should not lose focus after attempting to resolve front-end validation

### ISSUE THREAD

**Issue by jonwaldstein** [impress-org/givewp-next-gen#42]
## Details

Currently there is a strange bug around front-end validation.  When you submit the form with an invalid field, when you attempt to resolve the error the input will lose focus after the first keystroke. 

## Additional Context

I'm not exactly sure what's going on yet, but from initial investigation, it seems to be related to our dynamic fields being inside our Form component which call inline template related functions inside their render function. This could possibly be affecting the input refs since the Form children are re-rendered when the errors object changes from context.

I found some other discussions around this on RHF.

- https://github.com/react-hook-form/react-hook-form/discussions/7530
- https://github.com/react-hook-form/react-hook-form/discussions/7660

## Acceptance Criteria

-   [ ] Inputs do not lose focus after attempting to resolve front-end validation

**Comment by JasonTheAdams** [comment]
It probably has to do with the fact that we're using the FormProvider. If we follow their docs and use proper memoization, I bet that will fix it: https://react-hook-form.com/advanced-usage/#FormProviderPerformance

**Comment by jonwaldstein** [comment]
@JasonTheAdams we've used the RHF `FormProvider` plenty of times in the past to build forms and never had to memo nested inputs.  Even if we used memo, the component would still re-render on error which would result in the underlying issue.   I think the problem lies somewhere in our architecture and i'm almost positive it's from our dynamic components being generated inside the `SectionNodes` component.  Since we're dynamically creating components _inside_ render (using `getTemplate()`), there is bound to be side affects.  I think making sure those components are only created once, would solve the issue.

<img width="983" alt="Screen Shot 2022-07-26 at 11 04 07 AM" src="https://user-images.githubusercontent.com/10138447/181041522-6bfda79f-8596-4b1b-be7f-91bf0d1dfeaf.png">

**Comment by JasonTheAdams** [comment]
Since the nodes don't ever change, the entire `SectionNodes` component could be memoized. Basically, we can go up the chain until we're looping through the nodes, and that entire block can be memoized.

**Comment by jonwaldstein** [comment]
@JasonTheAdams @kjohnson I was able to resolve this with `useMemo` for the getTemplate calls specifically.  I initially tried `React.memo` but it had some unexpected side effects.  `useMemo` is a lot more flexible and worked like a charm here.

<img width="891" alt="Screen Shot 2022-07-26 at 2 30 27 PM" src="https://user-images.githubusercontent.com/10138447/181084242-f839103a-c6d1-42b8-b6fc-6734999ad1f1.png">
